// A self-signed certificate for the loopback MCP listener.
//
// Claude Desktop and Claude Code refuse an MCP connector URL that is not
// https, and there is no loopback exemption — so a vault that only ever talks
// to its own machine still needs a certificate. That is the whole reason this
// file exists; nothing here is about protecting traffic that never leaves the
// host from eavesdroppers on it.
//
// Two decisions worth stating:
//
// The certificate is its own CA (`CA:TRUE`, self-signed). That means one file
// serves as both the server certificate and the trust anchor, so the client is
// pointed at the same PEM it is already being presented. Verified: Node
// refuses it with DEPTH_ZERO_SELF_SIGNED_CERT until that file is in
// NODE_EXTRA_CA_CERTS, then accepts it for both localhost and 127.0.0.1.
//
// The private key is generated by the daemon, inside the vault directory, and
// never crosses the uid boundary. The CLI asks for the certificate — public
// material — and writes that where the client can read it. An agent running as
// the human can read the trust anchor, which tells it nothing, and cannot read
// the key, which would let it impersonate the vault.

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, chmodSync, statSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

const DAYS = 825 // the longest a leaf certificate may be trusted on macOS

export function tlsPaths(dir) {
  const d = join(dir, 'tls')
  return { dir: d, key: join(d, 'localhost-key.pem'), cert: join(d, 'localhost.pem') }
}

/**
 * Generate the certificate if it is missing or expired.
 * @returns {{cert: string, key: string, pem: string, fingerprint: string, notAfter: string, created: boolean}}
 */
export function ensureCertificate(dir, { force = false } = {}) {
  const p = tlsPaths(dir)
  if (!force && existsSync(p.cert) && existsSync(p.key) && !isExpiring(p.cert)) {
    return { ...describe(p.cert), cert: p.cert, key: p.key, created: false }
  }

  mkdirSync(p.dir, { recursive: true, mode: 0o700 })
  try {
    execFileSync('openssl', [
      'req', '-x509', '-newkey', 'rsa:2048', '-nodes',
      '-keyout', p.key, '-out', p.cert,
      '-days', String(DAYS),
      '-subj', '/CN=agent-vault localhost',
      // Both names, because a client may reach the listener by either and a
      // certificate that only covers one produces a bare handshake failure.
      '-addext', 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1',
      '-addext', 'basicConstraints=critical,CA:TRUE',
      '-addext', 'keyUsage=critical,digitalSignature,keyCertSign',
      '-addext', 'extendedKeyUsage=serverAuth',
    ], { stdio: ['ignore', 'ignore', 'pipe'] })
  } catch (e) {
    const detail = e.stderr?.toString().trim().split('\n').pop() || e.message
    throw new Error(`openssl could not generate a certificate: ${detail}`)
  }

  // The key is the one thing here that matters. Node refuses to load a key it
  // cannot read, but nothing stops it loading one everybody can.
  chmodSync(p.key, 0o600)
  chmodSync(p.cert, 0o644)
  return { ...describe(p.cert), cert: p.cert, key: p.key, created: true }
}

/** True when the certificate is gone, unreadable, or within 30 days of expiry. */
function isExpiring(certPath) {
  try {
    const { notAfter } = describe(certPath)
    return Date.parse(notAfter) - Date.now() < 30 * 86400_000
  } catch { return true }
}

function describe(certPath) {
  const pem = readFileSync(certPath, 'utf8')
  const der = Buffer.from(pem.replace(/-----[^-]+-----/g, '').replace(/\s+/g, ''), 'base64')
  const fingerprint = createHash('sha256').update(der).digest('hex')
    .replace(/(..)(?=.)/g, '$1:').toUpperCase()
  let notAfter = null
  try {
    const out = execFileSync('openssl', ['x509', '-in', certPath, '-noout', '-enddate'], { encoding: 'utf8' })
    notAfter = new Date(out.split('=')[1].trim()).toISOString()
  } catch { /* the fingerprint is still useful without it */ }
  return { pem, fingerprint, notAfter }
}

/** Material for https.createServer, with the key's permissions checked first. */
export function loadMaterial({ cert, key }) {
  for (const p of [cert, key]) if (!existsSync(p)) throw new Error(`tls file not found: ${p}`)
  const mode = statSync(key).mode & 0o777
  if (mode & 0o077) {
    throw new Error(`tls key ${key} is mode ${mode.toString(8)}; it must not be readable by others`)
  }
  return { cert: readFileSync(cert), key: readFileSync(key) }
}
